---
- name: Deploy App
  hosts: "{{ variable_hosts }}"
  vars:
    ansistrano_keep_releases: 10
    # There seems to be an issue with rsync in vagrant
    ansistrano_deploy_via: download
  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }
