- hosts: "{{ variable_hosts }}"
  user: chens
  tasks:
    - name: Install the package "mongodb"
      become: true
      apt:
        name: mongodb
        state: present
      register: out
    - debug: msg={{ out.stdout }}
