---
- name: ANSISTRANO | Check BC for early adopters
  fail:
    msg: "ansistrano_custom_tasks_path is not used anymore. Please, check the documentation at https://github.com/ansistrano/deploy"
  when: ansistrano_custom_tasks_path is defined

- include: "download-hooks/before_setup.yml"
  when: ansistrano_before_setup_tasks_file is defined

- include: setup.yml

- include: "download-hooks/after_setup.yml"
  when: ansistrano_after_setup_tasks_file is defined

- include: "download-hooks/before_symlink.yml"
  when: ansistrano_before_symlink_tasks_file is defined

- include: symlink.yml

- include: "download-hooks/after_symlink.yml"
  when: ansistrano_after_symlink_tasks_file is defined

- include: "download-hooks/before_cleanup.yml"
  when: ansistrano_before_cleanup_tasks_file is defined

- include: cleanup.yml

- include: "download-hooks/after_cleanup.yml"
  when: ansistrano_after_cleanup_tasks_file is defined
