---
- name: ANSISTRANO | Unarchive | Unarchive source
  command: tar -zxf "{{ ansistrano_archived_file  }}"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"

- name: ANSISTRANO | Unarchive | Delete archived file
  file:
    path: "{{ ansistrano_archived_file }}"
    state: absent