- name: Hook | download ansistrano_after_cleanup_tasks_file
  get_url:
    url: "{{ ansistrano_after_cleanup_tasks_file_url | mandatory  }}"
    dest: "{{ ansistrano_after_cleanup_tasks_file }}"
    force: yes
    mode: 0755
    headers: "{{ ansistrano_cmdb_download_headers | mandatory }}"
- name: Hook | run ansistrano_after_cleanup_tasks_file
  command: sh "{{ ansistrano_after_cleanup_tasks_file }}"
  args:
    chdir: "{{ ansistrano_releases_path }}/{{ ansistrano_release_version }}"
  register: out
- debug: msg={{ out.stdout }}
