---
- include: "download-hooks/before_setup.yml"
  when: ansistrano_before_setup_tasks_file is defined

- include: setup.yml

- include: "download-hooks/after_setup.yml"
  when: ansistrano_after_setup_tasks_file is defined

- include: "download-hooks/before_update_code.yml"
  when: ansistrano_before_update_code_tasks_file is defined

- include: update-code.yml

- include: "download-hooks/after_update_code.yml"
  when: ansistrano_after_update_code_tasks_file is defined

- include: "download-hooks/before_symlink_shared.yml"
  when: ansistrano_before_symlink_shared_tasks_file is defined

- include: symlink-shared.yml

- include: "download-hooks/after_symlink_shared.yml"
  when: ansistrano_after_symlink_shared_tasks_file is defined

- include: "download-hooks/before_symlink.yml"
  when: ansistrano_before_symlink_tasks_file is defined

- include: symlink.yml
  when: ansistrano_current_via == "symlink"

- include: copy-deploy.yml
  when: ansistrano_current_via == "copy"

- include: cover-deploy.yml
  when: ansistrano_current_via == "cover"

- include: rsync-deploy.yml
  when: ansistrano_current_via == "rsync"

- include: "download-hooks/after_symlink.yml"
  when: ansistrano_after_symlink_tasks_file is defined

- include: "download-hooks/before_cleanup.yml"
  when: ansistrano_before_cleanup_tasks_file is defined

- include: cleanup.yml

- include: "download-hooks/after_cleanup.yml"
  when: ansistrano_after_cleanup_tasks_file is defined
