---
# Update code deployment step
- name: ANSISTRANO | Get release version
  set_fact:
    ansistrano_release_version: "{{ lookup('pipe', 'date -u +%Y%m%d%H%M%SZ') }}"
  run_once: true
  when: ansistrano_release_version is not defined
  delegate_to: 127.0.0.1

- name: ANSISTRANO | Get release path
  command: echo "{{ ansistrano_releases_path }}/{{ ansistrano_release_version }}"
  register: ansistrano_release_path

- include: "update-code/{{ ansistrano_deploy_via | default('rsync') }}.yml"

- include: "download_config_files.yml"
  when: ansistrano_cmdb_config_files_get_url is defined

- name: ANSISTRANO | Copy release version into REVISION file
  copy:
    content: "{{ ansistrano_release_version }}"
    dest: "{{ ansistrano_release_path.stdout }}/REVISION"
